version: '3'

services:
  gateway:
    build: './gateway/dockerfile'
    ports:
      - "4000:4000"
  identityapi:
    build: './backend/dockerfile'
    ports:
      - "4000:4000"
  jaeger:
    image: jaegertracing/all-in-one:1.20
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"